name: water_tracker_app
description: Firebase oriented project, to connect and use most of this features.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6

  #firebase
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  firebase_analytics: ^10.0.8
  firebase_crashlytics: ^3.0.8
  cloud_firestore: ^4.2.0
  firebase_storage: ^11.0.10
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^3.0.9
  firebase_dynamic_links: ^5.0.11

  google_sign_in: ^5.4.2
  flutter_facebook_auth: ^5.0.6

  #state
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  percent_indicator: ^4.2.2

  image_picker: ^0.8.6

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  mockito: ^5.3.2
  firebase_auth_mocks: ^0.9.3
  google_sign_in_mocks: ^0.2.1
  build_runner: 2.3.0
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/google_logo.svg
    - assets/icons/facebook_logo.svg
    - assets/images/glass_of_water.png